name: Run Daily AI Agent

on:
  schedule:
    - cron: "30 4 * * *"  # Runs daily at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  run-agent:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run agent
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python main.py
